require('signals.arrange')
require('signals.focus')
require('signals.manage')
require('signals.mouse.enter')
require('signals.property.geometry')
require('signals.request.titlebars')
require('signals.unfocus')
require('signals.property.urgent')
